/**
 * `KeyboardEvent.code` values, as the event log records them (INV-089).
 *
 * These are DOM literals, not copy — the browser is what names them, so two of
 * the entries below (the apostrophe and backtick keys) are the only places
 * under WP-08's paths where the DoD-07 vocabulary grep matches something that
 * cannot be renamed without breaking key handling.
 *
 * The on-screen keymap (`qwertyKeycodeKeymap`) and the hand-split sets
 * (`leftSideKeys`, `rightSideKeys`) are gone with the keymap feature — nothing
 * imported them.
 */
export type Keycode =
  | "Backquote"
  | "Digit1"
  | "Digit2"
  | "Digit3"
  | "Digit4"
  | "Digit5"
  | "Digit6"
  | "Digit7"
  | "Digit8"
  | "Digit9"
  | "Digit0"
  | "Minus"
  | "Equal"
  | "Tab"
  | "KeyQ"
  | "KeyW"
  | "KeyE"
  | "KeyR"
  | "KeyT"
  | "KeyY"
  | "KeyU"
  | "KeyI"
  | "KeyO"
  | "KeyP"
  | "BracketLeft"
  | "BracketRight"
  | "Backslash"
  | "KeyA"
  | "KeyS"
  | "KeyD"
  | "KeyF"
  | "KeyG"
  | "KeyH"
  | "KeyJ"
  | "KeyK"
  | "KeyL"
  | "Semicolon"
  | "Quote"
  | "KeyZ"
  | "KeyX"
  | "KeyC"
  | "KeyV"
  | "KeyB"
  | "KeyN"
  | "KeyM"
  | "Comma"
  | "Period"
  | "Slash"
  | "Space"
  | "ShiftLeft"
  | "IntlBackslash"
  | "ShiftRight"
  | "ArrowUp"
  | "ArrowLeft"
  | "ArrowDown"
  | "ArrowRight"
  | "NumpadMultiply"
  | "NumpadSubtract"
  | "NumpadAdd"
  | "NumpadDecimal"
  | "NumpadEqual"
  | "NumpadDivide"
  | "Numpad0"
  | "Numpad1"
  | "Numpad2"
  | "Numpad3"
  | "Numpad4"
  | "Numpad5"
  | "Numpad6"
  | "Numpad7"
  | "Numpad8"
  | "Numpad9"
  | "NumpadEnter"
  | "Enter"
  | "Backspace";
