/**
 * Azure DocumentDB (Azure Cosmos DB for MongoDB **vCore**) — INF-057 … INF-062,
 * as amended by the user decision of 2026-08-02 ("just host mongodb via azure,
 * even though this will result in some costs").
 *
 * This module replaces the former `mongodb-atlas` module. The `mongodbatlas`
 * provider is gone from the stack, and with it blocker BL-4 (no Atlas org, no
 * Atlas programmatic API key pair) — the cluster is now an ordinary Azure
 * resource created by the same `azurerm` credentials as everything else.
 *
 * WHY vCore AND NOT THE RU API (evidence, INF-056 amended):
 *   The RU/serverless API does not list `$setWindowFields` in its aggregation
 *   stage table at all, marks `$bucket` unsupported, and documents that
 *   `$lookup` with `let`/`pipeline` fails with "`let` isn't supported".
 *   croco calc uses all three. vCore lists every one of them as supported.
 *   See docs/requirements/06-infra-and-ops.md §3 for the citations.
 *
 * TIERS:
 *   "M10"  — 1 burstable vCore / 2 GiB, ~$18.18/mo compute in westeurope plus
 *            ~$4.38/mo for 32 GiB of storage. Backups (<=35 days) included.
 *   "Free" — $0 forever, 32 GiB, one per subscription, but NOT offered in
 *            westeurope and with no backup/restore and no HA. Selecting it
 *            requires moving this one resource to a free-tier region
 *            (northeurope is the nearest); the validation below enforces that
 *            pairing so the combination cannot be applied by accident.
 */

terraform {
  required_version = "~> 1.14"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.65"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.9"
    }
  }
}

variable "resource_group_name" { type = string }

variable "location" {
  description = <<-EOT
    Region for the cluster. Normally `westeurope`, co-located with the Container
    App (INF-005). The ONLY reason to diverge is tier = "Free", which Azure does
    not offer in westeurope.
  EOT
  type        = string
}

variable "tags" { type = map(string) }

variable "cluster_name" {
  type    = string
  default = "mongo-croco-calc-prod"
}

variable "tier" {
  description = <<-EOT
    Compute tier. INF-062: the whole cost decision is this one variable.
    "M10" is the default (paid, westeurope, backups included).
    "Free" is the $0 lever and forces a free-tier region.
  EOT
  type        = string
  default     = "M10"

  validation {
    condition     = contains(["Free", "M10", "M20", "M25", "M30"], var.tier)
    error_message = "tier must be one of Free, M10, M20, M25, M30."
  }

  # A wrong tier/region pairing is otherwise silent until apply fails deep in
  # ARM, so catch it at plan time. https://learn.microsoft.com/en-us/azure/documentdb/free-tier
  validation {
    condition = var.tier != "Free" || contains([
      "francecentral", "germanynorth", "northeurope", "norwayeast",
      "switzerlandnorth", "brazilsouth", "canadacentral", "centralus",
      "eastus", "westus", "westus2", "australiacentral2", "australiaeast",
      "centralindia", "southindia", "eastasia", "japaneast", "japanwest",
    ], var.location)
    error_message = "Azure DocumentDB's free tier is not offered in every region — westeurope in particular. Pair tier = \"Free\" with location = \"northeurope\" (nearest to westeurope), or use tier = \"M10\"."
  }
}

variable "storage_size_in_gb" {
  description = "Free tier is fixed at 32 GiB; paid tiers may grow. Storage can only ever be increased, never shrunk."
  type        = number
  default     = 32
}

variable "mongo_version" {
  description = "Server version presented over the wire. 8.0 is the newest vCore offers and is a superset of what the DAL uses."
  type        = string
  default     = "8.0"
}

variable "db_name" {
  type    = string
  default = "crococalc"
}

variable "db_username" {
  type    = string
  default = "crococalcapi"
}

# INF-060: generated by Terraform, never typed by a human, never committed. The
# only place the value comes to rest is Key Vault.
#
# The vCore admin password is passed through a URI, so the character set is
# restricted to what needs no percent-encoding.
resource "random_password" "db" {
  length           = 40
  special          = true
  override_special = "-_"
  min_lower        = 1
  min_upper        = 1
  min_numeric      = 1
  min_special      = 1
}

resource "azurerm_mongo_cluster" "this" {
  name                = var.cluster_name
  resource_group_name = var.resource_group_name
  location            = var.location
  tags                = var.tags

  administrator_username = var.db_username
  administrator_password = random_password.db.result

  compute_tier       = var.tier
  storage_size_in_gb = var.storage_size_in_gb
  shard_count        = 1
  version            = var.mongo_version

  # Free tier does not support HA at all, and on M10 enabling it roughly doubles
  # the compute bill — which the $50 ceiling (INF-004) does not have room for.
  # Durability for v1 rests on the platform's own <=35-day backups (paid tiers)
  # plus the weekly mongodump of INF-061.
  high_availability_mode = "Disabled"

  # INF-059 (amended): ACA Consumption outside a VNet has no stable outbound IP,
  # and a NAT gateway to get one costs ~$32/mo — more than the database. Access
  # is therefore carried by SCRAM-SHA-256 credentials over mandatory TLS, the
  # same posture the Atlas design used, with the same reasoning.
  public_network_access = "Enabled"

  lifecycle {
    # Losing this cluster means losing every user, result and leaderboard.
    prevent_destroy = true
  }
}

resource "azurerm_mongo_cluster_firewall_rule" "anywhere" {
  name             = "allow-aca-egress"
  mongo_cluster_id = azurerm_mongo_cluster.this.id
  start_ip_address = "0.0.0.0"
  end_ip_address   = "255.255.255.255"
}

locals {
  # vCore requires `retrywrites=false`: the server rejects the retryable-write
  # flag the Node driver sets by default, so a URI carrying `retryWrites=true`
  # (as the Atlas one did) fails on the first write.
  connection_options = "tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000"
}

output "connection_string" {
  description = "Full SRV URI including credentials. Only ever written to Key Vault."
  value       = "mongodb+srv://${var.db_username}:${random_password.db.result}@${azurerm_mongo_cluster.this.name}.global.mongocluster.cosmos.azure.com/${var.db_name}?${local.connection_options}"
  sensitive   = true
}

output "cluster_id" {
  value = azurerm_mongo_cluster.this.id
}

output "cluster_name" {
  value = azurerm_mongo_cluster.this.name
}

output "tier" {
  value = var.tier
}

output "location" {
  value = var.location
}
