/**
 * MongoDB Atlas project, cluster, database user and network access (INF-057 …
 * INF-062).
 *
 * BLOCKER BL-4: no Atlas organisation or programmatic API key pair exists yet,
 * so this module has never been applied. Everything here is written against the
 * documented provider schema and validated offline.
 *
 * Tier selection is one variable (INF-062). The INF-058 probe decides:
 *   probe passes -> "M0"   (free shared tier, 512 MB)
 *   probe fails  -> "FLEX" (~$8/mo at the base ops tier)
 * No third option is pre-approved.
 */

terraform {
  required_version = "~> 1.14"
  required_providers {
    mongodbatlas = {
      source  = "mongodb/mongodbatlas"
      version = "~> 2.15"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.9"
    }
  }
}

variable "org_id" { type = string }
variable "project_name" {
  type    = string
  default = "croco-calc"
}
variable "cluster_name" {
  type    = string
  default = "croco-calc"
}
variable "tier" {
  type = string
  validation {
    condition     = contains(["M0", "FLEX"], var.tier)
    error_message = "tier must be \"M0\" or \"FLEX\"."
  }
}
variable "region" {
  type    = string
  default = "EUROPE_WEST"
}
variable "db_name" {
  type    = string
  default = "crococalc"
}
variable "db_username" {
  type    = string
  default = "crococalc-api"
}

locals {
  is_flex = var.tier == "FLEX"
}

resource "mongodbatlas_project" "this" {
  name   = var.project_name
  org_id = var.org_id
}

# INF-060: generated by Terraform, never typed by a human, never committed. The
# only place the value comes to rest is Key Vault.
resource "random_password" "db" {
  length  = 40
  special = false # SCRAM works either way; avoids URI-escaping the password.
}

# --- M0 (free shared tier) -------------------------------------------------
resource "mongodbatlas_advanced_cluster" "m0" {
  count = local.is_flex ? 0 : 1

  project_id     = mongodbatlas_project.this.id
  name           = var.cluster_name
  cluster_type   = "REPLICASET"
  backup_enabled = false # M0 has no automated backups; see INF-061.

  replication_specs = [{
    region_configs = [{
      provider_name         = "TENANT"
      backing_provider_name = "AZURE"
      region_name           = var.region
      priority              = 7

      electable_specs = {
        instance_size = "M0"
      }
    }]
  }]
}

# --- Flex fallback (INF-058) ----------------------------------------------
resource "mongodbatlas_flex_cluster" "flex" {
  count = local.is_flex ? 1 : 0

  project_id = mongodbatlas_project.this.id
  name       = var.cluster_name

  provider_settings = {
    backing_provider_name = "AZURE"
    region_name           = var.region
  }

  termination_protection_enabled = true
}

# INF-060: readWrite on exactly one database, no atlasAdmin.
resource "mongodbatlas_database_user" "api" {
  project_id         = mongodbatlas_project.this.id
  username           = var.db_username
  password           = random_password.db.result
  auth_database_name = "admin"

  roles {
    role_name     = "readWrite"
    database_name = var.db_name
  }
}

# INF-059: ACA Consumption outside a VNet has no stable egress IP, and a NAT
# gateway would cost ~$32/mo and breach the headroom rule. Security is carried
# by SCRAM credentials plus TLS.
resource "mongodbatlas_project_ip_access_list" "anywhere" {
  project_id = mongodbatlas_project.this.id
  cidr_block = "0.0.0.0/0"
  comment    = "ACA Consumption has no stable egress IP (INF-059)"
}

locals {
  srv_host = local.is_flex ? (
    replace(mongodbatlas_flex_cluster.flex[0].connection_strings.standard_srv, "mongodb+srv://", "")
    ) : (
    replace(mongodbatlas_advanced_cluster.m0[0].connection_strings.standard_srv, "mongodb+srv://", "")
  )
}

output "connection_string" {
  description = "Full SRV URI including credentials. Only ever written to Key Vault."
  value       = "mongodb+srv://${var.db_username}:${random_password.db.result}@${local.srv_host}/${var.db_name}?retryWrites=true&w=majority"
  sensitive   = true
}

output "project_id" {
  value = mongodbatlas_project.this.id
}

output "cluster_name" {
  value = var.cluster_name
}

output "tier" {
  value = var.tier
}
